CREATE TABLE "Usuario" (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Nome`	TEXT NOT NULL UNIQUE,
	`Email`	TEXT UNIQUE
)

CREATE TABLE "TipoAtendimento" (
       `ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
       `Label`	INTEGER NOT NULL UNIQUE
)

CREATE TABLE "Atendimento" (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Tipo`	INTEGER NOT NULL,
	`IDUsuario`	INTEGER NOT NULL,
	`Mensagem`	TEXT,
	`Data`	TEXT NOT NULL,
	FOREIGN KEY(`Tipo`) REFERENCES `TipoAtendimento`(`ID`),
	FOREIGN KEY(`IDUsuario`) REFERENCES `Usuario(ID)`
)

