CREATE TABLE "Atendimento" (
`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
`Tipo`	INTEGER NOT NULL,
`Nome`	TEXT NOT NULL,
`Mensagem`	TEXT,
`Data`	TEXT NOT NULL,
FOREIGN KEY(`Tipo`) REFERENCES TipoAtendimento(ID)
)

CREATE TABLE `TipoAtendimento` (
`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
`Label`	INTEGER NOT NULL
)
